name: Node.js CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ec2-16-171-237-214.eu-north-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.9.0'

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@ec2-16-171-237-214.eu-north-1.compute.amazonaws.com "source ~/.nvm/nvm.sh && cd laif-frontend && git pull && npm install && npm run build"
          scp -i ~/.ssh/id_rsa -r dist/ ubuntu@ec2-16-171-237-214.eu-north-1.compute.amazonaws.com:/var/www/html/my-vue-app
          ssh -i ~/.ssh/id_rsa ubuntu@ec2-16-171-237-214.eu-north-1.compute.amazonaws.com "sudo nginx -s reload"
